global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["host.docker.internal:8081"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "listing-service"
    static_configs:
      - targets: ["host.docker.internal:8082"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "order-service"
    static_configs:
      - targets: ["host.docker.internal:8083"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "ai-service"
    static_configs:
      - targets: ["host.docker.internal:8084"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "notification-service"
    static_configs:
      - targets: ["host.docker.internal:8085"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "chat-gateway"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
    metrics_path: "/metrics"
