name: Deploy Staging

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: deploy/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: deploy/terraform
        run: terraform plan -var-file=env/staging.tfvars
        env:
          TF_VAR_environment: staging

      - name: Terraform Apply
        working-directory: deploy/terraform
        run: terraform apply -auto-approve -var-file=env/staging.tfvars
        env:
          TF_VAR_environment: staging
